name: C/C++ CI

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make
      run: make
    - name: make test
      run: make test
    - name: 42_test
      run: ./42TESTERS-PRINTF/runtest.sh
