name: C/C++ CI

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: move
      run: cd ./42TESTERS-PRINTF
    - name: 42_test
      run: bash runtest.sh ../
